# Generated by Django 2.2 on 2019-04-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.IntegerField(choices=[(1, 'GitHub'), (2, 'GitLab'), (10, 'Unknown')], default=10, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_id',
            field=models.CharField(default=10, max_length=255, verbose_name='Project ID'),
            preserve_default=False,
        ),
    ]
