# Generated by Django 2.2 on 2019-04-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190402_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'platform']},
        ),
    ]
