language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
before_script:
  - mysql -e 'create database test;' -u root
script:
  - 'flake8'
  - 'python manage.py test'
