language: python
python:
  - '3.6'
env:
  global:
    - DB_ENGINE=django.db.backends.mysql
    - DB_NAME=techfolio
    - DB_USER=techfolio_usr
    - DB_PASS=techfolio_pwd
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
install:  
  - 'pip install pipenv'
  - 'pipenv install --dev'
before_script:
  - mysql -e 'create database test;' -u root
script:
  - 'flake8'
  - 'python manage.py test'
