# Generated by Django 2.2 on 2019-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('from_name', models.CharField(
                    max_length=255,
                    verbose_name='Sender name'
                )),
                ('from_email', models.EmailField(
                    max_length=254,
                    verbose_name='Sender address'
                )),
                ('subject', models.CharField(
                    max_length=255,
                    verbose_name='Subject'
                )),
                ('content', models.TextField(verbose_name='Message')),
                ('status', models.IntegerField(
                    choices=[
                        (1, 'Received'),
                        (2, 'Replied'),
                        (3, 'Waiting for anwser'),
                        (4, 'Closed')
                    ],
                    default=1,
                    verbose_name='Status'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
